
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fewqpgedjhvvbjgjtejj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZld3FwZ2Vkamh2dmJqZ2p0ZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTk5MDcsImV4cCI6MjA1Nzc5NTkwN30.KPDUtTRXCHExRzoyNG7vHcCHsm0n08n7yb8d1VFGP44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
